[package]
name = "async-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = { version = "1.13.2", features = ["unstable"]}
serde = {version = "1.0.228", features = ["derive", "rc"]}
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["sync"] }
